/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ShieldInterface extends utils.Interface {
  functions: {
    "createPolicy(bytes32,address,uint256,uint256)": FunctionFragment;
    "isPolicyValid(bytes32)": FunctionFragment;
    "logAttempt(bytes32,bool)": FunctionFragment;
    "policies(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createPolicy"
      | "isPolicyValid"
      | "logAttempt"
      | "policies"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createPolicy",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isPolicyValid",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "logAttempt",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPolicyValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logAttempt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;

  events: {
    "PolicyCreated(bytes32,address,address,uint256,uint256)": EventFragment;
    "VerificationAttempt(bytes32,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PolicyCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VerificationAttempt"): EventFragment;
}

export interface PolicyCreatedEventObject {
  policyId: string;
  sender: string;
  recipient: string;
  expiry: BigNumber;
  maxAttempts: BigNumber;
}
export type PolicyCreatedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  PolicyCreatedEventObject
>;

export type PolicyCreatedEventFilter = TypedEventFilter<PolicyCreatedEvent>;

export interface VerificationAttemptEventObject {
  policyId: string;
  success: boolean;
}
export type VerificationAttemptEvent = TypedEvent<
  [string, boolean],
  VerificationAttemptEventObject
>;

export type VerificationAttemptEventFilter =
  TypedEventFilter<VerificationAttemptEvent>;

export interface Shield extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShieldInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createPolicy(
      policyId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      maxAttempts: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isPolicyValid(
      policyId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    logAttempt(
      policyId: PromiseOrValue<BytesLike>,
      success: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    policies(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, number, number, boolean] & {
        sender: string;
        recipient: string;
        expiry: BigNumber;
        maxAttempts: number;
        attempts: number;
        valid: boolean;
      }
    >;
  };

  createPolicy(
    policyId: PromiseOrValue<BytesLike>,
    recipient: PromiseOrValue<string>,
    expiry: PromiseOrValue<BigNumberish>,
    maxAttempts: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isPolicyValid(
    policyId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  logAttempt(
    policyId: PromiseOrValue<BytesLike>,
    success: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  policies(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, number, number, boolean] & {
      sender: string;
      recipient: string;
      expiry: BigNumber;
      maxAttempts: number;
      attempts: number;
      valid: boolean;
    }
  >;

  callStatic: {
    createPolicy(
      policyId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      maxAttempts: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    isPolicyValid(
      policyId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    logAttempt(
      policyId: PromiseOrValue<BytesLike>,
      success: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    policies(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, number, number, boolean] & {
        sender: string;
        recipient: string;
        expiry: BigNumber;
        maxAttempts: number;
        attempts: number;
        valid: boolean;
      }
    >;
  };

  filters: {
    "PolicyCreated(bytes32,address,address,uint256,uint256)"(
      policyId?: PromiseOrValue<BytesLike> | null,
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      expiry?: null,
      maxAttempts?: null
    ): PolicyCreatedEventFilter;
    PolicyCreated(
      policyId?: PromiseOrValue<BytesLike> | null,
      sender?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      expiry?: null,
      maxAttempts?: null
    ): PolicyCreatedEventFilter;

    "VerificationAttempt(bytes32,bool)"(
      policyId?: PromiseOrValue<BytesLike> | null,
      success?: null
    ): VerificationAttemptEventFilter;
    VerificationAttempt(
      policyId?: PromiseOrValue<BytesLike> | null,
      success?: null
    ): VerificationAttemptEventFilter;
  };

  estimateGas: {
    createPolicy(
      policyId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      maxAttempts: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isPolicyValid(
      policyId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    logAttempt(
      policyId: PromiseOrValue<BytesLike>,
      success: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    policies(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createPolicy(
      policyId: PromiseOrValue<BytesLike>,
      recipient: PromiseOrValue<string>,
      expiry: PromiseOrValue<BigNumberish>,
      maxAttempts: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isPolicyValid(
      policyId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    logAttempt(
      policyId: PromiseOrValue<BytesLike>,
      success: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    policies(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
